//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by XGame.rc
//
#define ID_BTN_ALL                      2
#define ID_BTN_NONE                     3
#define IDC_BTN_NEWCOUNT                3
#define ID_SIM                          4
#define ID_BTN_PRODUCEMOON              4
#define ID_BTN_TRANSFER                 5
#define ID_BTN_PRODUCEGATE              6
#define ID_BTN_DESTROYCOLONY            7
#define ID_BTN_TRADE                    8
#define ID_BTN_HELP                     9
#define ID_BTN_ALL_WAR                  9
#define ID_BTN_ALL_BANJIA               10
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_XGAME_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDD_LOGIN_DIALOG                129
#define IDD_PAGE1_PERSON_INFO           130
#define IDD_PAGE2_BUILDINGS             131
#define IDI_ICON_MINAL_FACTORY          132
#define IDI_ICON_MINAL                  134
#define IDB_BITMAP1                     135
#define IDB_BITMAP2                     137
#define IDB_BITMAP3                     138
#define IDB_BITMAP4                     139
#define IDB_BITMAP5                     140
#define IDR_MENU_BUILDING               141
#define IDR_MENU_REDOURCE_PERCENT       141
#define IDI_ICON_CRYCALFACTORY          142
#define IDI_ICON_DIPOFACTORY            143
#define IDI_ICON_SUNPOWERFACTORY        144
#define IDI_ICON_ROBERTFACTORY          145
#define IDI_ICON_LABFACTORY             146
#define IDD_PAGE3_RESOURCE              147
#define IDR_SHELL_MENU                  148
#define IDI_ICON_ACCOUNT                149
#define IDI_ICON_PASSWORD               150
#define IDI_ICON_BOATYARD               151
#define IDD_DIALOG_GALAXY               152
#define IDD_DIALOG_BOATYARD             153
#define IDD_DIALOG_RESEARCH_CENTER      154
#define IDD_DIALOG_COMMANDER            155
#define IDD_DIALOG_INFOMATION           156
#define IDI_ICON1_STAR                  157
#define IDI_ICON2_STAR                  158
#define IDI_ICON3_STAR                  159
#define IDI_ICON4_STAR                  160
#define IDI_ICON5_STAR                  161
#define IDI_ICON6_STAR                  162
#define IDI_ICON7_STAR                  163
#define IDI_ICON8_STAR                  164
#define IDI_ICON9_STAR                  165
#define IDI_ICON10                      166
#define IDI_ICON10_STAR                 166
#define IDI_TECH_ICON_COMPUTER          167
#define IDI_TECH_ICON_ATTACK            168
#define IDI_TECH_ICON_BURNING           169
#define IDI_TECH_ICON_POWER             170
#define IDI_TECH_ICON_PULSE             171
#define IDI_TECH_ICON_RADIO             172
#define IDI_TECH_ICON_SPY               173
#define IDI_BOAT_HEAVY_FIGHTER          174
#define IDI_BOAT_LIGHT_FIGHTER          175
#define IDI_BOAT_SMALL_SCUTTER          176
#define IDI_BOAT_SPY_PLANET             177
#define IDI_BOAT_SUNPOWER_PLANET        178
#define IDR_GALAXY_MENU                 179
#define IDD_DIALOG_CONFIRM_ATTACK       181
#define IDI_BOAT_LARGESCUTTER           183
#define IDI_BOAT_CRUISOR                184
#define IDI_BOAT_WARSHIP                185
#define IDB_BIT_GUI_MAIN                186
#define IDI_GUI_BOATYARD                187
#define IDI_GUI_COMMAND                 188
#define IDI_GUI_INFORMATION             189
#define IDI_GUI_RESEARCH                191
#define IDI_GUI_RESOURCE                192
#define IDI_GUI_FACTORY                 194
#define IDC_CUR_LIST                    195
#define IDI_GUI_PERSON                  197
#define IDI_GUI_GALAXY                  198
#define IDD_DIALOG_SHOW_DETAILS         200
#define IDI_GUI_DOCUMENTS               201
#define IDI_GUI_SHIPS                   202
#define IDI_ICON_NATITEFACTORY          204
#define IDD_JOB_FINISH_TIP              207
#define IDB_CLK_0                       220
#define IDB_CLK_1                       221
#define IDB_CLK_2                       222
#define IDB_CLK_3                       223
#define IDB_CLK_4                       224
#define IDB_CLK_5                       225
#define IDB_CLK_6                       226
#define IDB_CLK_7                       227
#define IDB_CLK_8                       228
#define IDB_CLK_9                       229
#define IDB_CLK_BACK                    230
#define IDB_CLK_POINT                   231
#define IDB_BITMAP_CHECKMARK            232
#define IDB_BITMAP_EDITMARK             233
#define IDI_TECH_ICON_SHEILED           235
#define IDI_TECH_ICON_DEFENSE           236
#define IDI_BOAT_CONOLY                 237
#define IDI_BOAT_RECYCLE                238
#define IDI_BOAT_BOMBER                 239
#define IDI_BOAT_DESTROYER              240
#define IDI_BOAT_DS                     241
#define IDI_TECH_ICON_SUPERTECH         242
#define IDI_TECH_ICON_SUPERSPACE        243
#define IDI_TECH_ICON_DENGLIZI          244
#define IDI_TECH_ICON_GRAVITION         245
#define IDR_MENU_FLEETLIST              246
#define IDD_DLG_TRANSFER_BY_SUPERGATE   248
#define IDD_DIALOG_NEWACCOUNT           249
#define IDD_DIALOG_FIND_FORGETPASSWORD  250
#define IDD_DIALOG_TRADE_CENTER         251
#define IDD_DIALOG_ACCOUNT_INFO         253
#define IDD_DIALOG_DEFENSE              254
#define IDI_ICON_MISS                   255
#define IDI_ICON_SLASER                 256
#define IDI_ICON_HLASER                 257
#define IDI_ICON_GAUSS                  258
#define IDI_ICON_IONC                   259
#define IDI_ICON_PC                     260
#define IDI_GUI_DEFENSE                 261
#define IDC_COMBO1                      1003
#define IDC_EDIT2                       1004
#define IDC_COMBO_SPEED                 1004
#define IDC_LIST1                       1005
#define IDC_COMBO_FASTSTAR              1005
#define IDC_LIST_TASK_LIST              1006
#define IDC_LIST_TASK_ENEMY             1007
#define IDC_STA_MINAL                   1008
#define IDC_STA_CRY                     1009
#define IDC_BTN_BUILD                   1009
#define IDC_STA_DIP                     1010
#define IDC_STA_INFO                    1010
#define IDC_STA_POWER                   1011
#define IDC_STA_BUILD_INFO              1011
#define IDC_STA_RANK                    1012
#define IDC_PROGRESS1                   1012
#define IDC_STA_BUILD_TIMER             1013
#define IDC_STA_PRODUCE_RATIO           1013
#define IDC_STA_BUINGING_ICON           1014
#define IDC_STA_TEMP                    1014
#define IDC_STA_REG_TIME                1014
#define IDC_BTN_CANCEL                  1015
#define IDC_BTN_DELETE                  1015
#define IDC_BTN_OK                      1015
#define IDC_BTN_CLEAR                   1016
#define IDC_BTN_CANCEL2                 1016
#define IDC_BTN_COPY                    1016
#define IDC_BUTTON3                     1017
#define IDC_LIST_TASK                   1017
#define IDC_EDIT1                       1018
#define IDC_STA_RESEARCHING_ICON        1019
#define IDC_EDIT_METAL                  1019
#define IDC_EDIT_PASSWORD               1019
#define IDC_EDIT_AVAI_C                 1019
#define IDC_EDIT_THANKLIST              1019
#define IDC_STA_RESEARCH_INFO           1020
#define IDC_EDIT_CRYSTAL                1020
#define IDC_EDIT_PASSWORDAGAIN          1020
#define IDC_EDIT_AVAI_D                 1020
#define IDC_EDIT_ACCOUNT_INFO           1020
#define IDC_STA_RESEARCH_TIMER          1021
#define IDC_EDIT_DIOP                   1021
#define IDC_EDIT_STAR_NAME              1021
#define IDC_EDIT_M                      1021
#define IDC_BTN_RESEARCH                1022
#define IDC_EDIT_SYS                    1022
#define IDC_EDIT_STAR_NAME2             1022
#define IDC_EDIT_C                      1022
#define IDC_EDIT_NPC_NAME               1022
#define IDC_STA_MAX_TASKS               1023
#define IDC_EDIT_D                      1023
#define IDC_STA_IS_MAX                  1024
#define IDC_STATIC1                     1024
#define IDC_EDIT_TRADE_PERCENT          1024
#define IDC_STATIC2                     1025
#define IDC_EDIT_POS                    1025
#define IDC_EDIT_TRADE_MONEY            1025
#define IDC_STATIC3                     1026
#define IDC_STATIC4                     1027
#define IDC_STATIC5                     1028
#define IDC_STATIC6                     1029
#define IDC_LIST_DETAILS                1030
#define IDC_EDIT_TRADE_POUNDAGE         1030
#define IDC_TREE1                       1032
#define IDC_EDIT_DEFAULT                1033
#define IDC_BTN_SET_DEFAULT             1034
#define IDC_STATIC_TRANSFER             1035
#define IDC_STATIC_ATTACK               1036
#define IDC_STATIC_TIME                 1038
#define IDC_STATIC_OIL                  1039
#define IDC_STATIC_STAR_METAL           1040
#define IDC_LIST_PROGRESS               1041
#define IDC_STATIC_STAR_CRYSTAL         1041
#define IDC_RADIO1                      1042
#define IDC_RADIO2                      1043
#define IDC_RADIO3                      1044
#define IDC_STATIC_STAR_DIOP            1045
#define IDC_STATIC_LEAVE_POS            1046
#define IDC_BTN_METAL_MAX               1047
#define IDC_BTN_CRYSTAL_MAX             1048
#define IDC_BTN_DIOP_MAX                1049
#define IDC_RADIO4                      1050
#define IDC_RADIO5                      1051
#define IDC_EDIT_GALA                   1052
#define IDC_STATIC_MOON                 1053
#define IDC_STATIC_GATE                 1054
#define IDC_BTN_COLONY1                 1055
#define IDC_STATIC_LEFT_CAPACITY        1055
#define IDC_BTN_COLONY2                 1056
#define IDC_BTN_GALA_LEFT               1056
#define IDC_BTN_COLONY3                 1057
#define IDC_BTN_GALA_RIGHT              1057
#define IDC_BTN_ALL_RESOURCE            1057
#define IDC_BTN_HOMESTAR                1058
#define IDC_BTN_SYS_LEFT                1058
#define IDC_BTN_SYS_RIGHT               1059
#define IDC_RADIO6                      1059
#define IDC_BTN_SHOW                    1060
#define IDC_EDIT_SHOW_GALA              1061
#define IDC_EDIT_SHOW_SYS               1062
#define IDC_COMBO2                      1064
#define IDC_BTN_SPYS                    1065
#define IDC_CHECK                       1066
#define IDC_EDIT_NAME                   1067
#define IDC_BTN_FORGET_PASSWORD         1068
#define IDC_EDIT_ACCOUNTNAME            1069
#define IDC_BTN_DELETE_ACCOUNT          1069
#define IDC_BTN_UPDATE                  1070
#define IDC_BTN_FIND                    1071
#define IDC_BTN_GO                      1071
#define IDC_BTN_GO_TARGET               1072
#define IDC_BTN_UPDATERANK              1073
#define IDC_BTN_CRY_MAX                 1074
#define IDC_STA_METAL                   1075
#define IDC_BTN_ALL_MAX                 1076
#define IDC_EDIT_AVAI_M                 1077
#define IDC_STA_DIOP                    1078
#define IDC_EDIT_SPEED                  1078
#define IDC_STA_MONEY                   1079
#define IDC_CHECK1                      1079
#define IDC_CHECK_RESOURCE              1080
#define IDC_BTN_ACCOUNT_INFO            1080
#define ID_MENU_BUILDING_BUILD          32771
#define ID_MENU_RESOURCE_P100           32771
#define ID_MENU_RESOURCE_P90            32772
#define ID_MENU_RESOURCE_P80            32773
#define ID_MENU_RESOURCE_P70            32774
#define ID_MENU_RESOURCE_P60            32775
#define ID_MENU_RESOURCE_P50            32776
#define ID_MENU_RESOURCE_P40            32777
#define ID_MENU_RESOURCE_P30            32778
#define ID_MENU_RESOURCE_P20            32779
#define ID_MENU_RESOURCE_P10            32780
#define ID_MENU_RESOURCE_P00            32781
#define IDR_SHELL_MENU_DISPLAY          32782
#define IDR_SHELL_MENU_EXIT             32783
#define ID_MENU_GALAXY_SPY              32784
#define ID_MENU_GALAXY_ATTACK           32785
#define ID_MENU_FLEET_CALLBACK          32786
#define ID_MENU_GALAXY_VIEW_RANK        32787
#define IDR_SHELL_MENU_SILENTMODE       32788
#define IDR_SHELL_MENU_SETTING          32789
#define IDR_SHELL_MENU_EXITWHENALLOVER  32790
#define IDR_SHELL_MENU_GALAXYUPDATETIME 32800
#define IDR_SHELL_MENU_RANK             32801
#define IDR_SHELL_MENU_TRADE            32802
#define IDR_SHELL_MENU_GATE             32803
#define IDR_SHELL_MENU_ABOUT            32804
#define IDR_SHELL_MENU_ACCOUNT_RANK     32805
#define IDR_SHELL_MENU_SAVE_DISABLE     32807
#define IDR_SHELL_MENU_SAVE_60          32808
#define IDR_SHELL_MENU_SAVE_50          32809
#define IDR_SHELL_MENU_SAVE_40          32810
#define IDR_SHELL_MENU_SAVE_30          32811
#define IDR_SHELL_MENU_SAVE_20          32812
#define IDR_SHELL_MENU_SAVE_10          32813
#define IDR_SHELL_MENU_SAVE_05          32814
#define IDR_SHELL_MENU_SAVE             32816
#define IDR_SHELL_MENU_ACCOUNT_INFO     32817
#define IDR_SHELL_MENU_DISPLAY_DEFENSE  32818
#define ID_MENU_GALAXY_RECYCLE          32820

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        262
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
